HOST_IP = "127.0.0.1"
HOST_PORT = 44444

WATCH_SCREEN_COMMAND = 'Watch Screen'
WATCH_WEBCAM_COMMAND = 'Watch Web Cam'
INSTALL_RANSOMWARE_COMMAND = 'Install Ransomware'
UNINSTALL_RANSOMWARE_COMMAND = 'Fix Ransomware'